require'plug-config.icons'
require'plug-config.lualine'
require'plug-config.treesitter'
require'plug-config.telescope'
require'plug-config.nerdtree'
require'plug-config.nvim-comment'
require'plug-config.nvim-autopairs'
require'plug-config.indent-blankline'
require'plug-config.sniprun'
require'plug-config.fugitive'
require'plug-config.gitsigns'
require'plug-config.project'
require'plug-config.nvim-sessions'
require'plug-config.formatter'
require'plug-config.luasnip'

require'plug-config.lsp'
