require 'plug-config.icons'
require 'plug-config.lualine'
require 'plug-config.nerdtree'
require 'plug-config.gitsigns'
require 'plug-config.nvim-comment'
require 'plug-config.nvim-autopairs'
require 'plug-config.fugitive'
require 'plug-config.diffview'
require 'plug-config.telescope'
require 'plug-config.formatter'
require 'plug-config.luasnip'

require 'plug-config.mason'
require 'plug-config.lsp'
